name: Releaser

on:
  release:
    types: [ published ]

jobs:

  actions-tagger:
    name: Action Tag
    runs-on: ubuntu-latest
    steps:

      - name: Publish tag
        uses: Actions-R-Us/actions-tagger@v2

  publish-npm:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@worksome'

      - name: Install npm dependencies
        run: npm install

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
